import datetime
now = datetime.datetime.now()
date = now.strftime("%d-%m-%y %H:%M:%S")

item_bought = input("Enter the product being purchased: ")
token = input("Enter the token number: ")
amount = input("Enter the amount requested by customers: ")
units = float(amount) * 1.9026
tax = 13.04
cost = float(amount) - float(tax)
total = float(cost) + float(tax)
receipt_number = input("Enter receipt number: ")
voucher_ID = input("Enter voucher ID: ")
customer = input("Enter the names of the customer: ")
customer_account = input("Enter the customer's Account number: ")
meter_number = input("Enter the customer's meter number: ")
print("         The power of prepared           ")
print("-" * 45)
print("     Superspar City Centre       ")
print("         Tax Invoice         ")
print("-" * 45)
print("     Polokwane Municipality      ")
print("         VAT No. 4700193560          ")
print("-" * 45)
print(item_bought)
print("-" * 45)
print(token)
print("-" * 45)
print(f'    {units} Kwh @ {1.9026} R/Kwh:')
print("-" * 45)
print(f'Amount:             R{ cost}')
print(f'Tax:                R{tax}')
print("-" * 45)
print(f'Total:              R{total}')
print("-" * 45)
print(f'Grand Total:        R{total}')
print("-" * 45)
print(f'    Total Units : {units}')
print("-" * 45)
print(f'Receipt No:       {receipt_number}')
print(f'Date      :       {date}')
print(f'Voucher ID:       {voucher_ID}')
print("-" * 45)
print(f'Customer:       {customer}')
print("Tariff:          1 (Domestic)")
print(f'Acc No:         {customer_account}')
print(f'Meter No:       {meter_number}')
print("Tok Tech:    02    ALG: 07")
print("SGC     :    000100  KRN:    2   TI: 1")
print("-" * 45)
print("     Need a prepaid electricity")
print("   advances%3F Dial *130*6266# to")
print("     check eligibility. T&Cs at")
print("         www.bluadvance.co.za")
print("     -Print Done-")
